# 3.3.1 다차원 배열

다차원 배열도 그 기본은 "숫자의 집합"이다.

In [2]:
import numpy as np

A = np.array([1, 2, 3, 4])

print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


이는 지금까지 보아온 1차원 배열이다.

(ex. x = np.arange(-5, 5, 0.1)

배열의 차원수는 np.ndim() 메소드를 활용해 알 수 있다. 배열의 형상은 shape 메소드를 활용해 알 수 있다.

In [3]:
B = np.array([[1, 2], [3, 4], [5, 6]])

print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


이는 2차원 배열인데, 행렬(Matrix) 라고도 부른다.

# 3.3.2 행렬의 곱

우선 $2 \times 2$ 행렬의 곱을 살펴보면, 

$
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix} 
\quad = \quad
\begin{pmatrix}
19 & 22 \\
43 & 50
\end{pmatrix}
$

이와 같이 계산한다.

행렬의 곱은 왼쪽 행렬의 row 벡터에 오른쪽 행렬의 column 벡터의 내적을 구해 칸을 채우게 한다.

$
\begin{pmatrix}
\begin{bmatrix}
1 & 2
\end{bmatrix} \\
\begin{bmatrix}
3 & 4
\end{bmatrix}
\end{pmatrix}
\begin{pmatrix}
\begin{bmatrix}
5 \\ 7
\end{bmatrix} &
\begin{bmatrix}
6 \\ 8
\end{bmatrix}
\end{pmatrix}
\quad = \quad
\begin{pmatrix}
\begin{bmatrix}
1 & 2
\end{bmatrix}^T
\begin{bmatrix}
5 & 7
\end{bmatrix} &
\begin{bmatrix}
1 & 2
\end{bmatrix}^T
\begin{bmatrix}
6 & 8
\end{bmatrix} \\
\begin{bmatrix}
3 & 4
\end{bmatrix}^T
\begin{bmatrix}
5 & 7
\end{bmatrix} &
\begin{bmatrix}
3 & 4
\end{bmatrix}^T
\begin{bmatrix}
6 & 8
\end{bmatrix}
\end{pmatrix}
$

In [4]:
A = np.array([[1, 2], [3, 4]])
print(A.shape)

B = np.array([[5, 6],  [7, 8]])
print(B.shape)

print(A@B)

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


행렬 곱을 할 때의 유의할 점은 항상 왼쪽 행렬의 열의 갯수와 오른쪽 행렬의 행의 갯수를 일치시켜야 한다는 점이다.

예를 들어, $2 \times 2$ 행렬과 $3 \times 2$ 행렬은 행렬 곱을 연산할 수 없지만 순서를 바꿔 $3 \times 2$ 행렬과 $2 \times 2$ 행렬은 행렬 곱 연산을 할 수 있다.

이는 벡터와 행렬의 곱에서도 마찬가지이다.

# 3.3.3 신경망에서의 행렬 곱

<img src="images/3_14.png" height="300px" width="700px">

위 그림과 같이 간단한 신경망의 예를 들어보자. 이 신경망은 편향과 활성화 함수를 생략하고 가중치만을 가진다.

위 경우처럼, "@" 연산자를 사용하면 행렬의 곱을 수행해준다.
이를 통해 3개의 값을 가지는 $y$일지언정, 한번의 계산으로 결과를 얻어낼 수 있다.